version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - acubismmotion
  - Aerisita
  - airi
  - airi-vtuber
  - Attributify
  - audioworklet
  - awilix
  - Ayaka
  - baichuan
  - baiducloud
  - bigserial
  - Bitstream
  - browserbasehq
  - bumpp
  - catppuccin
  - changelogithub
  - cientos
  - collectblock
  - composables
  - crossws
  - csmmap
  - csmvector
  - cubismbreath
  - cubismdebug
  - cubismdefaultparameterid
  - cubismeyeblink
  - cubismmatrix44
  - cubismmoc
  - cubismmodelsettingjson
  - cubismmotionqueuemanager
  - cubismusermodel
  - cubismviewmatrix
  - cuteen
  - deepseek
  - defu
  - demi
  - devlogs
  - dotenvx
  - dtype
  - dtypes
  - duckdb
  - DuckDBWASM
  - DuckDBWASMQ
  - DuckDBWASMQuery
  - elevenlabs
  - Factorio
  - formkit
  - gcornut
  - giteeai
  - gltf
  - gpuu
  - grammyjs
  - groq
  - guiiai
  - hfspaceup
  - hfsup
  - hfup
  - higress
  - histoire
  - hiyori
  - huggingface
  - huggingspace
  - hunyuan
  - hyoban
  - iconify
  - intlify
  - Kawaii
  - kwaa
  - libsodium
  - listhen
  - live2dcubismcore
  - live2dcubismframework
  - Llmmarker
  - lobehub
  - logg
  - lucide
  - Maru
  - micvad
  - mineflayer
  - mingcute
  - mkdist
  - moeru
  - Morioki
  - Myriam
  - Neko
  - nekomeowww
  - neuri
  - Neuro
  - Neuro-sama
  - nomic
  - novita
  - nuxi
  - nuxt
  - nuxtjs
  - ofetch
  - ollama
  - Oneliner
  - onnx
  - onnxruntime
  - openai
  - openrouter
  - OPFS
  - opusscript
  - pgvector
  - picklist
  - picovoice
  - pinia
  - pixi
  - pixiv
  - popmotion
  - pretrained
  - prismarine
  - pthread
  - qwen
  - rehype
  - rushstack
  - Saccade
  - saccades
  - SAVEPOINT
  - sensenova
  - Shadcn
  - shiki
  - shikijs
  - silero
  - siliconcloud
  - sizecheck
  - smallserial
  - Sniglet
  - stepfun
  - supergroup
  - superjson
  - tamagotchi
  - taze
  - tolist
  - tresjs
  - typeschema
  - unhead
  - unocss
  - unplugin
  - valibot
  - vaul
  - VITE
  - vllm
  - vrma
  - vueuse
  - wavefile
  - webgpu
  - worklet
  - Xenova
  - xsai
  - zhipu
ignoreWords: []
import: []
