version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - acubismmotion
  - airi
  - airi-vtuber
  - Attributify
  - Ayaka
  - bumpp
  - cientos
  - composables
  - csmmap
  - csmvector
  - cubismbreath
  - cubismdebug
  - cubismdefaultparameterid
  - cubismeyeblink
  - cubismmatrix44
  - cubismmoc
  - cubismmodelsettingjson
  - cubismmotionqueuemanager
  - cubismusermodel
  - cubismviewmatrix
  - cuteen
  - defu
  - demi
  - dtype
  - elevenlabs
  - formkit
  - gltf
  - hfspaceup
  - hfsup
  - hfup
  - histoire
  - hiyori
  - huggingface
  - huggingspace
  - iconify
  - intlify
  - kwaa
  - live2dcubismcore
  - live2dcubismframework
  - Llmmarker
  - Maru
  - micvad
  - Myriam
  - Neko
  - nekomeowww
  - Neuro
  - Neuro-sama
  - nuxi
  - nuxt
  - nuxtjs
  - ofetch
  - onnx
  - onnxruntime
  - openai
  - picklist
  - pinia
  - pixi
  - pixiv
  - pretrained
  - rehype
  - shiki
  - shikijs
  - silero
  - sizecheck
  - Sniglet
  - taze
  - tresjs
  - typeschema
  - unhead
  - unocss
  - unplugin
  - valibot
  - VITE
  - vrma
  - vueuse
  - webgpu
  - worklet
  - xsai
  - hfup
ignoreWords: []
import: []
