# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

edition = "2024"
tab_spaces = 2
imports_indent = "Block" # nightly
match_arm_leading_pipes = "Preserve"
# empty_item_single_line = true # nightly
group_imports = "StdExternalCrate" # nightly
imports_granularity = "Crate" # nightly
imports_layout = "HorizontalVertical" # nightly
# match_arm_blocks = false # nightly
match_block_trailing_comma = true
# normalize_comments = true # nightly
# normalize_doc_attributes = true # nightly
# overflow_delimited_expr = true # nightly
# reorder_impl_items = true # nightly
# spaces_around_ranges = true # nightly
unstable_features = true # nightly
use_field_init_shorthand = true
use_try_shorthand = true
struct_field_align_threshold = 999
enum_discrim_align_threshold = 999
# max_width = 512
chain_width = 50
fn_params_layout = "Vertical"
single_line_if_else_max_width = 25
