"$schema" = "schemas/schema.json"

[default]
description = """
This permission set configures what kind of
operations are available from the mcp plugin.

#### Granted Permissions

All operations are enabled by default.
"""
permissions = [
  "allow-load-ort-model-whisper",
  "allow-ipc-audio-transcription",
]
